
package com.drugstore.client.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2-hudson-752-
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DrugstoreWS", targetNamespace = "http://ws.server.drugstore.com/", wsdlLocation = "http://localhost:8080/DrugstoreWS/DrugstoreWS?wsdl")
public class DrugstoreWS_Service
    extends Service
{

    private final static URL DRUGSTOREWS_WSDL_LOCATION;
    private final static WebServiceException DRUGSTOREWS_EXCEPTION;
    private final static QName DRUGSTOREWS_QNAME = new QName("http://ws.server.drugstore.com/", "DrugstoreWS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/DrugstoreWS/DrugstoreWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DRUGSTOREWS_WSDL_LOCATION = url;
        DRUGSTOREWS_EXCEPTION = e;
    }

    public DrugstoreWS_Service() {
        super(__getWsdlLocation(), DRUGSTOREWS_QNAME);
    }

   
    public DrugstoreWS_Service(URL wsdlLocation) {
        super(wsdlLocation, DRUGSTOREWS_QNAME);
    }


    public DrugstoreWS_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

  

    /**
     * 
     * @return
     *     returns DrugstoreWS
     */
    @WebEndpoint(name = "DrugstoreWSPort")
    public DrugstoreWS getDrugstoreWSPort() {
        return super.getPort(new QName("http://ws.server.drugstore.com/", "DrugstoreWSPort"), DrugstoreWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DrugstoreWS
     */
    @WebEndpoint(name = "DrugstoreWSPort")
    public DrugstoreWS getDrugstoreWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.server.drugstore.com/", "DrugstoreWSPort"), DrugstoreWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DRUGSTOREWS_EXCEPTION!= null) {
            throw DRUGSTOREWS_EXCEPTION;
        }
        return DRUGSTOREWS_WSDL_LOCATION;
    }

}
