/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PatientListForm.java
 *
 * Created on 25.Ara.2011, 22:19:34
 */
package com.drugstore.client.ui.patient;

import com.drugstore.client.DrugstoreWSClient;
import com.drugstore.client.ui.model.PatientTableModel;
import com.drugstore.client.ws.Patient;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.util.List;

/**
 *
 * @author ekisa
 */
public class PatientListForm extends javax.swing.JPanel implements PropertyChangeListener{

    private EditPatientForm editPatientForm;
    
    /** Creates new form PatientListForm */
    public PatientListForm() {
        initComponents();
        initData();
    }
    
    private boolean editPatient() {
        PatientTableModel model = (PatientTableModel) table.getModel();
        editPatientForm = new EditPatientForm(this, true);
        editPatientForm.addPropertyChangeListener("patientList", this);
        editPatientForm.editPatient(model.getRowData(table.getSelectedRow()));
        editPatientForm.setVisible(true);
        return false;
    }

    private boolean canEditPatient() {
        if (table.getSelectedRow() == -1) {
            return false;
        }
        return true;
    }

    @Override
    public void propertyChange(PropertyChangeEvent evt) {
        if (evt.getPropertyName().equals("patientList")) {
            this.initData();
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        patientTableModel1 = new com.drugstore.client.ui.model.PatientTableModel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        commandPanel = new javax.swing.JPanel();
        newBtn = new javax.swing.JButton();
        editBtn = new javax.swing.JButton();

        table.setModel(patientTableModel1);
        jScrollPane1.setViewportView(table);

        newBtn.setText("New");
        newBtn.setPreferredSize(new java.awt.Dimension(50, 25));
        newBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newBtnActionPerformed(evt);
            }
        });

        editBtn.setText("Edit");
        editBtn.setPreferredSize(new java.awt.Dimension(50, 25));
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout commandPanelLayout = new javax.swing.GroupLayout(commandPanel);
        commandPanel.setLayout(commandPanelLayout);
        commandPanelLayout.setHorizontalGroup(
            commandPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, commandPanelLayout.createSequentialGroup()
                .addContainerGap(494, Short.MAX_VALUE)
                .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(newBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        commandPanelLayout.setVerticalGroup(
            commandPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(commandPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(commandPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(135, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 717, Short.MAX_VALUE)
            .addComponent(commandPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(commandPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        if (canEditPatient()) {
            editPatient();
        }
    }//GEN-LAST:event_editBtnActionPerformed

    private void newBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newBtnActionPerformed
        editPatientForm = new EditPatientForm(this, true);
        editPatientForm.addPropertyChangeListener("patientList", this);
        editPatientForm.newPatient();
        editPatientForm.setVisible(true);
    }//GEN-LAST:event_newBtnActionPerformed

    public void initData() {
        List<Patient> listData = DrugstoreWSClient.getInstance().getWebService().getDrugstoreWSPort().listPatients();
        PatientTableModel model = (PatientTableModel) table.getModel();
        model.setData(listData);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel commandPanel;
    private javax.swing.JButton editBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton newBtn;
    private com.drugstore.client.ui.model.PatientTableModel patientTableModel1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
