/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DrugListForm.java
 *
 * Created on 24.Ara.2011, 21:39:59
 */
package com.drugstore.client.ui.drug;

import com.drugstore.client.DrugstoreWSClient;
import com.drugstore.client.ui.model.DrugTableModel;
import com.drugstore.client.ws.Drug;
import java.awt.AWTEvent;
import java.awt.Event;
import java.awt.EventQueue;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.beans.PropertyChangeSupport;
import java.util.ArrayList;
import java.util.List;
import javax.swing.SwingUtilities;
import javax.swing.SwingWorker;
import javax.swing.event.EventListenerList;
import javax.swing.event.SwingPropertyChangeSupport;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import org.jdesktop.observablecollections.ObservableCollections;

/**
 *
 * @author ekisa
 */
public class DrugListForm extends javax.swing.JPanel implements PropertyChangeListener{

    /** Creates new form DrugListForm */
    public DrugListForm() {
        initComponents();
        initData();
    }

    private boolean editDrug() {
        DrugTableModel model = (DrugTableModel) table.getModel();
        editDrugForm = new EditDrugForm(this, true);
        editDrugForm.addPropertyChangeListener("drugList", this);
        editDrugForm.editDrug(model.getRowData(table.getSelectedRow()));
        editDrugForm.setVisible(true);
        return false;
    }

    private boolean canEditDrug() {
        if (table.getSelectedRow() == -1) {
            return false;
        }
        return true;
    }
    
    @Override
    public void propertyChange(PropertyChangeEvent evt) {
        if (evt.getPropertyName().equals("drugList")) {
            this.initData();
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        editDrugForm = new com.drugstore.client.ui.drug.EditDrugForm();
        drugTableModel1 = new com.drugstore.client.ui.model.DrugTableModel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        editButton = new javax.swing.JButton();
        newButton = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();

        javax.swing.GroupLayout editDrugFormLayout = new javax.swing.GroupLayout(editDrugForm.getContentPane());
        editDrugForm.getContentPane().setLayout(editDrugFormLayout);
        editDrugFormLayout.setHorizontalGroup(
            editDrugFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        editDrugFormLayout.setVerticalGroup(
            editDrugFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setPreferredSize(new java.awt.Dimension(700, 450));

        table.setModel(drugTableModel1);
        table.setColumnSelectionAllowed(true);
        table.setFillsViewportHeight(true);
        jScrollPane1.setViewportView(table);
        table.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        table.getColumnModel().getColumn(0).setHeaderValue("Name");
        table.getColumnModel().getColumn(1).setHeaderValue("Code");
        table.getColumnModel().getColumn(2).setHeaderValue("Manufacturer");
        table.getColumnModel().getColumn(3).setHeaderValue("Prescription Type");
        table.getColumnModel().getColumn(4).setHeaderValue("Number of Pills");
        table.getColumnModel().getColumn(5).setHeaderValue("Owning Cost");
        table.getColumnModel().getColumn(6).setHeaderValue("Selling Cost");

        jPanel1.setPreferredSize(new java.awt.Dimension(700, 150));

        editButton.setText("Edit");
        editButton.setPreferredSize(new java.awt.Dimension(50, 25));
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        newButton.setText("New");
        newButton.setPreferredSize(new java.awt.Dimension(50, 25));
        newButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newButtonActionPerformed(evt);
            }
        });

        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(350, Short.MAX_VALUE)
                .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(newButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteBtn))
                .addContainerGap(125, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        if (canEditDrug()) {
            editDrug();
        }
    }//GEN-LAST:event_editButtonActionPerformed

    private void newButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newButtonActionPerformed
        editDrugForm = new EditDrugForm(this, true);
        editDrugForm.addPropertyChangeListener("drugList", this);
        editDrugForm.newDrug();
        editDrugForm.setVisible(true);
    }//GEN-LAST:event_newButtonActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        final DrugTableModel model = (DrugTableModel) table.getModel();
        int index = table.getSelectedRow();
        Drug itemToRemove = model.getRowData(index);
        DrugstoreWSClient.getInstance().getWebService().getDrugstoreWSPort().removeDrug(itemToRemove);
        model.removeData(index);
        table.repaint();
    }//GEN-LAST:event_deleteBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteBtn;
    private com.drugstore.client.ui.model.DrugTableModel drugTableModel1;
    private javax.swing.JButton editButton;
    private com.drugstore.client.ui.drug.EditDrugForm editDrugForm;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton newButton;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables

    public void initData() {
        List<Drug> listData = DrugstoreWSClient.getInstance().getWebService().getDrugstoreWSPort().listDrugs();
        DrugTableModel model = (DrugTableModel) table.getModel();
        model.setData(listData);
    }
}
