/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EditAlternativeDrugForm.java
 *
 * Created on 26.Ara.2011, 10:48:54
 */
package com.drugstore.client.ui.prescription;

import com.drugstore.client.domain.AlternativeDrug;
import com.drugstore.client.ui.model.AlternativeDrugTableModel;
import com.drugstore.client.util.DrugstoreClientUtil;
import com.drugstore.client.ws.Drug;
import com.drugstore.client.ws.PrescriptionLineItem;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;

/**
 *
 * @author ekisa
 */
public class EditAlternativeDrugForm extends javax.swing.JDialog {

    private List<AlternativeDrug> alternatives = new ArrayList<AlternativeDrug>();
    
    /** Creates new form EditAlternativeDrugForm */
    public EditAlternativeDrugForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
    }

    public EditAlternativeDrugForm() {
    }
    
    public EditAlternativeDrugForm(Map<PrescriptionLineItem, List<Drug>> alternativesMap, EditPrescriptionForm parent) {
        this(DrugstoreClientUtil.getTopFrame(), true);
        
        for(Iterator<PrescriptionLineItem> iterator = alternativesMap.keySet().iterator(); iterator.hasNext();){
            PrescriptionLineItem pli = iterator.next();
            List<Drug> drugs = alternativesMap.get(pli);
            for(Iterator<Drug> drugItearator = drugs.iterator(); drugItearator.hasNext();){
                Drug drug = drugItearator.next();
                AlternativeDrug alternativeDrug = new AlternativeDrug(pli, drug);
                this.alternatives.add(alternativeDrug);
            }
        }
        
        initComponents();
        initData();
        DrugstoreClientUtil.centerComponent(this);
        
        
    }
    
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        alternativeDrugTableModel1 = new com.drugstore.client.ui.model.AlternativeDrugTableModel();
        scollPaneOfTable = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        commandPanel = new javax.swing.JPanel();
        replaceBtn = new javax.swing.JButton();
        doneBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Select an Alternative");

        table.setModel(alternativeDrugTableModel1);
        scollPaneOfTable.setViewportView(table);
        table.getColumnModel().getColumn(0).setHeaderValue("Drug");
        table.getColumnModel().getColumn(1).setHeaderValue("Price Per Pill");
        table.getColumnModel().getColumn(2).setHeaderValue("Selling Cost");
        table.getColumnModel().getColumn(3).setHeaderValue("Suggested Alternative");
        table.getColumnModel().getColumn(4).setHeaderValue("Price Per Pill");
        table.getColumnModel().getColumn(5).setHeaderValue("Selling Cost");

        replaceBtn.setText("Replace Selected");
        replaceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                replaceBtnActionPerformed(evt);
            }
        });

        doneBtn.setText("Done");
        doneBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout commandPanelLayout = new javax.swing.GroupLayout(commandPanel);
        commandPanel.setLayout(commandPanelLayout);
        commandPanelLayout.setHorizontalGroup(
            commandPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, commandPanelLayout.createSequentialGroup()
                .addContainerGap(379, Short.MAX_VALUE)
                .addComponent(replaceBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(doneBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        commandPanelLayout.setVerticalGroup(
            commandPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(commandPanelLayout.createSequentialGroup()
                .addGroup(commandPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doneBtn)
                    .addComponent(replaceBtn))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(commandPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(scollPaneOfTable, javax.swing.GroupLayout.DEFAULT_SIZE, 595, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scollPaneOfTable, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(commandPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void doneBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_doneBtnActionPerformed

    private void replaceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_replaceBtnActionPerformed
        AlternativeDrug alternativeDrug = alternatives.get(table.getSelectedRow());
        alternatives.remove(table.getSelectedRow());
        table.repaint();
        firePropertyChange("replaceLineItem", alternativeDrug.getPli(), alternativeDrug.getDrug());
    }//GEN-LAST:event_replaceBtnActionPerformed

    public List<AlternativeDrug> getAlternatives() {
        return alternatives;
    }

    public void setAlternatives(List<AlternativeDrug> alternatives) {
        this.alternatives = alternatives;
    }

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.drugstore.client.ui.model.AlternativeDrugTableModel alternativeDrugTableModel1;
    private javax.swing.JPanel commandPanel;
    private javax.swing.JButton doneBtn;
    private javax.swing.JButton replaceBtn;
    private javax.swing.JScrollPane scollPaneOfTable;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables

    private void initData() {
        AlternativeDrugTableModel model = (AlternativeDrugTableModel) table.getModel();
        model.setData(alternatives);
    }
}
